server:
  port: 9090
  servlet:
    context-path: /uaa

logging:
  level:
    org.springframework.security: DEBUG

spring:
  security:
    user:
      name: user
      password: password
      roles: USER